[package]
name = "gpu_native"
version = "0.1.0"
edition = "2024"

[target.'cfg(not(target_arch = "nvptx64"))'.dependencies]
cudarc = { version = "0.12.2", default-features = false, features = ["cuda-12060", "driver"] }